feat:新增绀青主题
xitu/juejin-markdown-themes pull request #3
Opened 2020-11-06 03:29 UTC by linxsbox

新增了绀青主题
修改了 README.md 文件，新增了主题连接，新增了工具连接

2020-11-06 03:49 UTC, pd4d10 requested changes

2020-11-06 03:49 UTC, pd4d10 commented on .gitignore
> +gallery/themes.js
使用 `LF` 避免 diff

2020-11-06 03:49 UTC, pd4d10 commented on README.md
> +- [主题样式开发工具](https://github.com/linxsbox/juejin-theme)
工具代码可以直接提交到这个仓库里

2020-11-06 03:49 UTC, pd4d10 commented on README.md
> +- [主题样式开发工具](https://github.com/linxsbox/juejin-theme)
工具可以单独提一个 PR，更清晰一些

2020-11-06 13:10 UTC, linxsbox commented on README.md
> +- [主题样式开发工具](https://github.com/linxsbox/juejin-theme)
好，哪我建立一个叫 tools 的文件把工具放里面。
但是 package 需要独立吗？还是说和原有的 package 合并？

2020-11-06 13:11 UTC, linxsbox commented on .gitignore
> +gallery/themes.js
好的，我修改后再提交一下

2020-11-07 03:01 UTC, pd4d10 commented on README.md
> +- [主题样式开发工具](https://github.com/linxsbox/juejin-theme)
嗯，要不整合到这个 package 里？

2020-11-07 03:19 UTC, merged