feat: 增加channing-cyan主题
xitu/juejin-markdown-themes pull request #4
Opened 2020-11-06 08:01 UTC by ChanningHan

2020-11-06 08:08 UTC, lsvih commented
`.idea` 里的文件不需要添加

2020-11-06 08:34 UTC, ChanningHan commented
已删除

2020-11-06 10:11 UTC, pd4d10 requested changes

2020-11-06 10:11 UTC, pd4d10 commented on themes.js
> +  'channing-cyan': 'channing-cyan.sss',
背景图可以使用 base64 防止未来图片地址失效

2020-11-06 12:21 UTC, ChanningHan commented on themes.js
> +  'channing-cyan': 'channing-cyan.sss',
已替换

2020-11-07 03:27 UTC, pd4d10 requested changes

2020-11-07 03:27 UTC, pd4d10 commented on themes.js
> +  'channing-cyan': 'channing-cyan.sss',
https://github.com/ChanningHan/juejin-markdown-theme-channing-cyan/blob/8ba53e75232d8ab097fdaa25475305c7e14131d3/channing-cyan.scss#L329

这个图片还需要再处理一下

2020-11-07 05:13 UTC, ChanningHan commented on themes.js
> +  'channing-cyan': 'channing-cyan.sss',
已处理

2020-11-07 05:13 UTC, pd4d10 approved these changes

2020-11-07 05:13 UTC, merged

2020-11-08 03:34 UTC, pd4d10 commented
图片可以压缩一下吗 @ChanningHan 

``` sh
198K channing-cyan.css
```

注意到展示的时候并没有使用到那么大的尺寸